"""Replace Firebase with Supabase

Revision ID: 47d6a5a5380d
Revises: 392f39772d50
Create Date: 2026-07-10 21:27:40.476406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d6a5a5380d'
down_revision = '392f39772d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_path', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('file_url', sa.Text(), nullable=False))
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('firebase_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_url', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('file_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('file_url')
        batch_op.drop_column('storage_path')

    # ### end Alembic commands ###
